var A=(r,e,t)=>{if(!e.has(r))throw TypeError("Cannot "+t)};var g=(r,e,t)=>(A(r,e,"read from private field"),t?t.call(r):e.get(r)),n=(r,e,t)=>{if(e.has(r))throw TypeError("Cannot add the same private member more than once");e instanceof WeakSet?e.add(r):e.set(r,t)},p=(r,e,t,o)=>(A(r,e,"write to private field"),o?o.call(r,t):e.set(r,t),t);var y=(r,e,t)=>(A(r,e,"access private method"),t);import{S as I,i as v}from"./assets/vendor-beb23274.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))o(s);new MutationObserver(s=>{for(const a of s)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function t(s){const a={};return s.integrity&&(a.integrity=s.integrity),s.referrerPolicy&&(a.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?a.credentials="include":s.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(s){if(s.ep)return;s.ep=!0;const a=t(s);fetch(s.href,a)}})();var c,l,m,L;const u=class u{constructor(e){n(this,m);n(this,l,void 0);p(this,l,e)}searchImages(e){return y(this,m,L).call(this,"",e)}};c=new WeakMap,l=new WeakMap,m=new WeakSet,L=function(e,t){return fetch(g(u,c)+e+"?"+new URLSearchParams({key:g(this,l),...t})).then(o=>o.json())},n(u,c,"https://pixabay.com/api/");let f=u;const F="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAENSURBVHgBrZVhDoIwDIUrgfDXm+hRvBFwEr0BXsXjsJnMFVkYsvUV4SWL6Nr3MWgrUUbW2sYY6zSLY3M+Zc7cOWr9evqvL5J18av1OVRVVUdI4c6HwTxIKY5FJ/nbXA3ZYw4hR5hnIZK5MeaKDFMxC8jX3PapRPTi5lJOQWzPewHQpgz49xxkPrmcKwJyEGQe55UEVNdV64P5cmwm1tSEHe+hfAj4hUwAlTmrIKWKglzqGkl1gmg2hVmjnj0QEJuHxxK/EwiRqkGqFqmE433YaJpSFBttDnrfUxACSsWw1+LmJMhWrcyDjoBkzY+AQPM9EMl81QdhLJxOrvGfZ1L96bvblvExaj4JXtJj+QAn5UUxjHYd+gAAAABJRU5ErkJggg==";function Y(r){return r.map(e=>M(e)).join("")}function M({webformatURL:r,largeImageURL:e,tags:t,likes:o,views:s,comments:a,downloads:i}){let d=`<li class="gallery-item">
                <a class="gallery-image-link" href="${e}">
                    <img 
                        class="gallery-image" 
                        src="${r}" 
                        alt="${t}" 
                    />
                </a>
                <ul class="gallery-item-stats">`;for(const[S,U]of Object.entries({likes:o,views:s,comments:a,downloads:i}))d+=`<li class="gallery-item-stats-item">
                                <p class="gallery-item-stats-label">${S}</p>
                                <p class="gallery-item-stats-value">${U}</p>
                              </li>`;return d+="</ul></li>"}const R="25546966-f3ef2260a4c78c9f4c7cc9e45",b={image_type:"photo",orientation:"horizontal",safesearch:!0},B=new f(R),O=new I(".gallery a",{captionsData:"alt",captionDelay:250,captionsPosition:"bottom"}),P=document.querySelector("#search-form"),E=document.querySelector(".gallery"),w=document.querySelector(".loader");function j(){w.classList.remove("hidden")}function x(){w.classList.add("hidden")}P.addEventListener("submit",r=>{r.preventDefault();const e=r.currentTarget,t=e.searchField.value.trim();if(t===""){h("You have to write something!");return}E.innerHTML="",j(),B.searchImages({q:t,...b}).then(o=>{o.total===0?h("Sorry, there are no images matching your search query. Please try again!"):(E.innerHTML=Y(o.hits),O.refresh())}).catch(o=>{h(o.message)}).finally(()=>{x(),e.reset()})});function h(r){v.error({title:"Error",message:r,iconUrl:F,position:"topRight",titleColor:"#FFF",messageColor:"#FFF",backgroundColor:"#EF4040",theme:"dark",progressBar:!1,close:!1})}
//# sourceMappingURL=commonHelpers.js.map
